	/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "lcd.h"
#include "stm32f4xx.h"
#include "i2c.h"


void DelayUs(uint32_t us)
{
    // Using TIM2
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
    TIM2->PSC = 84 - 1;     // 1 MHz → 1us
    TIM2->ARR = 0xFFFFFFFF;
    TIM2->CR1 |= TIM_CR1_CEN;

    uint32_t start = TIM2->CNT;
    while ((TIM2->CNT - start) < us);
}

// --------- Ultrasonic GPIO Init ----------
void Ultrasonic_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    // PA0 = TRIG (Output)
    GPIOA->MODER &= ~(3 << (0*2));
    GPIOA->MODER |=  (1 << (0*2));

    // PA1 = ECHO (Input)
    GPIOA->MODER &= ~(3 << (1*2));
}

// --------- Get Echo Pulse Width ----------
uint32_t Ultrasonic_ReadEcho(void)
{
    // Send 10us TRIG pulse
    GPIOA->BSRR = (1 << 0);
    DelayUs(10);
    GPIOA->BSRR = (1 << (0 + 16));

    // Wait for ECHO = HIGH
    while (!(GPIOA->IDR & (1 << 1)));

    uint32_t start = TIM2->CNT;

    // Wait for ECHO = LOW
    while (GPIOA->IDR & (1 << 1));

    uint32_t end = TIM2->CNT;

    return (end - start);   // time in microseconds
}


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
int main(void)
{
    char str[20];
    uint16_t val = 0;     // fake variable to show on LCD

    DelayMs(20);
    LcdInit();
    LcdPuts(LCD_LINE1, "LCD TEST");
    LcdPuts(LCD_LINE2, "NO ADC USED");

    while(1)
    {
        val++;   // increasing number (simulating ADC)

        sprintf(str, "VALUE = %4d", val);
        LcdPuts(LCD_LINE2, str);

        DelayMs(300);
    }
}
*/
int main(void)
{
    char str[20];

    DelayMs(20);
    LcdInit();
    Ultrasonic_Init();   // <-- Added

    LcdPuts(LCD_LINE1, "Ultrasonic:");

    while (1)
    {
        uint32_t echo_time = Ultrasonic_ReadEcho();
        int distance = echo_time / 580;   // cm

        sprintf(str, "Dist: %dcm ", distance);
        LcdPuts(LCD_LINE2, str);

        DelayMs(300);
    }
    return 0;
}



